name: S3 Sync

on:
  push:
    branches:
      - main  # 対象のブランチを指定

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: ファイルのタイムスタンプを復元
        uses: chetan/git-restore-mtime-action@v2

      - name: AWS CLIをセットアップ
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ap-northeast-1  # 東京リージョン（変更可）

      - name: S3に同期、CloudFrontのキャッシュクリア
        run: |
          aws s3 sync --exclude '.git*' . s3://www3.murumoya.com --dryrun --delete > .github/update.log
          awk '$2=="upload:" {print $3}' .github/update.log > .github/upload_file.log
          echo "■アップロードするファイル"
          cat .github/upload_file.log
          aws s3 sync --exclude '.git*' . s3://www3.murumoya.com --exact-timestamps --delete
          aws cloudfront create-invalidation --distribution-id EZD24GW63GZSP --paths $(cat .github/upload_file.log | sed -E 's|^\./|/|;s|^[^/]|/&|' | xargs)
          # 上記のsedは、先頭が./の場合、/に置換、先頭が/以外の文字の場合、/を追加 を表す
